# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- azure-pipelines

resources:
- repo: self

steps:
    - task: FortifySCA@7
      inputs:
        licenseFile: 'C:\Users\Administrator\Downloads\Fortify.License'
        applicationType: 'other'
        fortifyBuildId: 'webgoat'
        runFortifyRulepackUpdate: false
        fortifyScanType: 'LocalScan'
        runBuildTranslate: true
        buildToolOptions: 'mvn com.fortify.sca.plugins.maven:sca-maven-plugin:translate'
        runFortifyClean: true
        scaVerbose: false
        scaDebug: false
        runFortifyScan: true
        fortifyApplicationName: 'WebGoat'
        fortifyApplicationVersion: '1'   
